In [3]:
import numpy as np
from sklearn import preprocessing

In [4]:
X = np.array([[ 1., -1., 2. ], 
              [ 2.,  0., 0. ],
              [ 0.,  1., -1.]])

In [9]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [8]:
X_scaled.std(axis = 0)

array([1., 1., 1.])

In [10]:
# better methodolgy as then we can use it for another data also such as testing data 
scaler = preprocessing.StandardScaler()  
# also there is min max scaler and absolute scaler   
scaler.fit(X)

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [13]:
X_test = [[1, 1, 2]]    
scaler.transform(X_test)    # it has scaled the data as per the parameters during you learned on the training data.

array([[0.        , 1.22474487, 1.33630621]])